name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-16.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.11.3
              otp: 23.2.5
            lint: lint
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install Dependencies
        run: mix deps.get --only test && mix deps.unlock --check-unused

      - name: Compile library
        run: mix compile --warnings-as-errors

      - run: mix test
